# Conduit app configuration
name: Paper
version: "1.0"
target: development
# Database - uncomment the next 6 lines if you're using MySQL and DDEV.
database:
  mysql:
    host: db
    user: db
    pass: db
    db: db
routes:
  "/":
    GET:
      middleware: Home
      template: index.twig
  "/login":
    GET:
      middleware: Auth_Login_GET
      template: login.twig
    POST:
      middleware: Auth_Login_POST
  "/logout":
    GET:
      middleware: Auth_Logout
plugins:
  ConduitUser:
    loginPage: "/login"
